""" EJEMPLO DE USO DE LA LIBRERÍA DE CÁLCULO DE ÁREAS """

"""
CAMBIO PARA QUE FUNCIONE
VA HA EJECUTAR ESTE CÓDIGO NUEVO AHORA

"""

"FERNANDO ME HA PEDIDO QUE CAMBIE ESTO AQUI, EL PAGARA LOS PLATOS ROTOS"

""" 
ESTO ES LO MIO, YA FUNCIONA, OTRO MES QUE NO COBRA FRAN

"""
