""" EJEMPLO DE USO DE LA LIBRERÍA DE CÁLCULO DE ÁREAS """

"""
CAMBIO PARA QUE FUNCIONE
VA HA EJECUTAR ESTE CÓDIGO NUEVO AHORA

"""

"FERNANDO ME HA PEDIDO QUE CAMBIE ESTO AQUI, EL PAGARA LOS PLATOS ROTOS"

""" 
ESTE ES EL DESARROLLO QUE VA HA HACER FRAN Y QUE ESPEREMOS FUNCIONE POR SU BIEN

"""
